# Generated by Django 4.2.23 on 2025-07-14 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('character', models.CharField(max_length=10)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=200)),
                ('poster_url', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('showtime', models.CharField(max_length=10)),
                ('release_date', models.CharField(max_length=10)),
                ('plot', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=10)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actors')),
            ],
        ),
    ]
