# Generated by Django 4.2.23 on 2025-07-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_director_image_url_remove_movies_actors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movies'),
        ),
    ]
