# Generated by Django 4.2.23 on 2025-07-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_username_comments_user_comments_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.AddField(
            model_name='actors',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movies.movies'),
        ),
    ]
